version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  backend:
    image: lechicong01/springppq:v3
    container_name: springppq-backend
    ports:
      - "8080:8080"
    volumes:
      - /var/www/ppq/upload:/app/upload
      - /var/www/ppq/logs:/app/logs
    environment:
      DB_URL: jdbc:mysql://mysqljava:3306/PPQ
      BASE_URL: http://baostar-286990.thuevpsgiare.com.vn:8080
      UPLOAD_BASE_PATH: /app/upload
      DB_USER: root
      DB_PASS: admin123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ALLOWED_ORIGINS: http://baostar-286990.thuevpsgiare.com.vn
      REDIRECT_URI: http://baostar-286990.thuevpsgiare.com.vn:8080/login/oauth2/code/google
      VIRTUAL_HOST: baostar-286990.thuevpsgiare.com.vn
      LETSENCRYPT_HOST: baostar-286990.thuevpsgiare.com.vn
      LETSENCRYPT_EMAIL: Lechicong9a2@gmail.com.com

    depends_on:
      mysqljava:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - ppq-network

  frontend:
    image: lechicong01/my-frontend:v3
    container_name: ppq-frontend
    restart: always
    environment:
      VIRTUAL_HOST: baostar-286990.thuevpsgiare.com.vn
      LETSENCRYPT_HOST: baostar-286990.thuevpsgiare.com.vn
      LETSENCRYPT_EMAIL: lechicong9a2@gmail.com
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - ppq-network

  mysqljava:
    image: mysql:8.0
    container_name: mysqljava
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: PPQ
    ports:
      - "3306:3306"
    networks:
      - ppq-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-padmin123" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ppq-network

networks:
  ppq-network:
    driver: bridge
