spring:
  datasource:
    url: jdbc:mysql://localhost:3307/PPQ
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:upload/

  mail:
    host: smtp.gmail.com
    port: 587
    username: lechicong20055@gmail.com  # email đúng của bạn
    password: pobccnntrfsqbbna           # App Password (đúng, không có khoảng trắng)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  # ◀ Bật STARTTLS
          ssl:
            trust: "smtp.gmail.com"  # ◀ Bắt buộc để xác thực chứng chỉ
          protocols: "TLSv1.2"  # ◀ Force dùng TLS 1.2+
security:
  authentication:
    jwt:
      base64-secret: WlSKedhlklTqSrR1VajEv/U46TLFKfLGqNk5d8MqfkNfyuHTuRpeu5bQCxxvvRlRk1G/F6WahwflnqKZP40KaQ==
      token-validity-in-seconds: 86400
app:
  base-url: ${BASE_URL:http://localhost:8080}

